### ISSUE TITLE
Lightning Talk: Building Serverless APIs with Go and AWS Lambda

### ISSUE THREAD

**Issue by acatighera** [nycgolang/meetups#10]
## Scheduling Details

Speaker(s): Alex Catighera

Topic(s): Building Serverless APIs with Go and AWS Lambda

I will quickly go through setting up API Gateway. As well as running through deploying a basic lambda function with http://apex.run/ that processes a web request. There will be some quick tips and tricks for API Gateway endpoint mapping, keeping lambdas "warm" & bootstrapping optimization.

Event Date/Title: Aug 23 Go Meetup

*If you are signing up to speak at already scheduled meetup, please provide the title of the meetup so that we can follow up with availability and update the appropriate agenda.*

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [x] Acquire a venue, if the talk is not part of an already scheduled event.
- [x] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [x] Draft of event started on Meetup.com
- [x] Confirm venue, sponsorship, and date.
- [x] Publish event to Meetup.com - Update event date above.
- [ ] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by nywilken** [comment]
@acatighera thanks for signing up to give a talk. The August event is pretty stacked with talks for the night so I’m going to hold off on accepting any new talks.  But it would be great to have you speak at the September event (probably the third or fourth week). Let me know if you’re interested.

**Comment by nywilken** [comment]
@acatighera any chance you want to speak at the October event?

**Comment by acatighera** [comment]
Sure, I can do that.

**Comment by nywilken** [comment]
Awesome I’ll add you as the second lightning talk. All the best.

**Comment by nywilken** [comment]
Scheduled for the October meetup. Thank you.

**Comment by acatighera** [comment]
The lightning talk should be 5 min duration? Just wanted to confirm

**Comment by nywilken** [comment]
We allocate 10 minutes for each lightning talk.
