### ISSUE TITLE
October 18th: Go Meetup

### ISSUE THREAD

**Issue by adranwit** [nycgolang/meetups#12]
## Scheduling Details

Speaker(s): 
Adrian Witas (full talk)

Topic(s): 
Engineer centric end to end testing with go lang.

Event Date/Title: October 18, 2018

*If you are signing up to speak at already scheduled meetup, please provide the title of the meetup so that we can follow up with availability and update the appropriate agenda.*

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [x] Acquire a venue, if the talk is not part of an already scheduled event.
- [x] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [x] Draft of event started on Meetup.com
- [x] Confirm venue, sponsorship, and date.
- [x] Publish event to Meetup.com - Update event date above.
- [x] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by nywilken** [comment]
@adranwit thanks again for signing up to speak at our October meetup. I am going to use this issue to track the event setup. We have confirmed the venue and sponsorship. I expect to have an actual event posted to meetups this week.

**Comment by adranwit** [comment]
@nywilken thanks for organizing the meetup

**Comment by nywilken** [comment]
@adranwit do you have a description for your talk?

**Comment by adranwit** [comment]
@nywilken Please find the description below:

Unit testing dominates quality assurance delivered by engineers, and only a few take on end to end testing automation. It has felt that complexity and lack of tools could be to blame.  Moreover, ETL testing focus is significantly different than web service or UI app. You might have used docker or web testers like Selenium or HTTP/REST runner, but this is just a small part of the story. Find out more about how to orchestrate and automate e2e testing tasks for your go app, all with Endly - fully declarative e2e testing framework.

[Presentation link](https://github.com/adrianwit/golang-e2e-testing/raw/master/golang-e2e.pptx)

**Comment by nywilken** [comment]
@adranwit please take a minute to answer our [speaker questionnaire](https://docs.google.com/forms/d/e/1FAIpQLScOMMNOGY4EFwqCNvBrCQlRL2N12HMgrCg6FweK6NNXhjAIqA/viewform)

Also do you have a little blurb about yourself or a twitter handle we can include in the event post?

**Comment by adranwit** [comment]
@nywilken I have just post meetup im with some more details, here is my tweeter account, https://twitter.com/adrian_witas
