### ISSUE TITLE
September or October: Dissecting Go Binaries

### ISSUE THREAD

**Issue by grantseltzer** [nycgolang/meetups#13]
## Scheduling Details

Speaker(s): Grant Seltzer (https://github.com/grantseltzer)

Topic(s): Dissecting Go Binaries

Event Date/Title: Either September or October (either works for me!) 

The purpose of this talk is to introduce listeners to how compiled Go binaries work by building a very short disassembler program together. The goal will be to make all related topics as easily accessible as possible. The talk will assume very little knowledge of compilers or assembly code. 

I will also be publishing a related blog post in the next few days and will link it here when I do! 

*If you are signing up to speak at already scheduled meetup, please provide the title of the meetup so that we can follow up with availability and update the appropriate agenda.*

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [x] Acquire a venue, if the talk is not part of an already scheduled event.
- [x] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [x] Draft of event started on Meetup.com
- [x] Confirm venue, sponsorship, and date.
- [x] Publish event to Meetup.com - Update event date above.
- [ ] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by nywilken** [comment]
@grantseltzer thnkas for signing up to speak. We will probably be able to get you slated for September. But to better help get you situated for the upcoming event could you take a few minutes to complete the [speaker questionnaire ](https://docs.google.com/forms/d/e/1FAIpQLScOMMNOGY4EFwqCNvBrCQlRL2N12HMgrCg6FweK6NNXhjAIqA/viewform)

**Comment by grantseltzer** [comment]
@nywilken I'm on it!

**Comment by grantseltzer** [comment]
@nywilken I for some reason took the "Topic(s)" field as tags and not as the name of the talk :-) 

I meant the title of the talk to be "Dissecting Go Binaries"

**Comment by nywilken** [comment]
All good. Thanks for the quick turn around Grant. I updated the title on the event posting.

**Comment by grantseltzer** [comment]
[Slides](https://docs.google.com/presentation/d/1Q73ISYRUM0zdqw4dD4HGXJ7dgnv3OD4u9qdqfLLUAfY/edit?usp=sharing)

[Related blog post](https://grantseltzer.github.io/dissecting-go-binaries/)

**Comment by nywilken** [comment]
Thanks again for the talk. Lots of good feedback about this talk. I created PR #15 to add the provided links to the talks page.
