### ISSUE TITLE
Lightning Talk: Debunking apprehensions around Golang Libraries & Frameworks

### ISSUE THREAD

**Issue by venkateshthallam** [nycgolang/meetups#16]
## Scheduling Details

Speaker(s): Venkatesh Thallam

Topic(s): Debunking apprehensions around Golang Libraries & Frameworks

I will talk about the apprehensions using frameworks or external libraries by Gophers and introduce few of the libraries/frameworks that perform better than the standard library and offer more flexibility in building micro-services.

Event Date/Title: Oct 18th Go Meetup

*If you are signing up to speak at already scheduled meetup, please provide the title of the meetup so that we can follow up with availability and update the appropriate agenda.*

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [x] Acquire a venue, if the talk is not part of an already scheduled event.
- [x] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [x] Draft of event started on Meetup.com
- [x] Confirm venue, sponsorship, and date.
- [x] Publish event to Meetup.com - Update event date above.
- [x] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by nywilken** [comment]
@venkateshthallam thanks for signing up to talk. The topic sounds great and will be especially helpful to a number of new members. To better help get you situated for the upcoming event could you take a few minutes to complete the [speaker questionnaire](
https://goo.gl/forms/Om4MAebK7TagwT3L2)

**Comment by nywilken** [comment]
Also do you have a little blurb about yourself or a twitter handle we can include in the event post?

**Comment by venkateshthallam** [comment]
Yes. Here's the blurb,

> [Venkatesh Thallam](https://twitter.com/vthallam) is a Senior Software Engineer at [PaperlessPost](https://twitter.com/paperlesspost) ,currently writing microservices in Go that help Paperless users meet more often in real-world.  He is passionate about distributed systems, tech products and their business impact, nature in no particular order.

I have hyperlinked my twitter handle and the company's handle, hope it's okay. 

Thanks for ordinating this.
