### ISSUE TITLE
November 29: Go-Giving

### ISSUE THREAD

**Issue by nywilken** [nycgolang/meetups#19]
## Scheduling Details

Speaker(s):

Topic(s):

Event Date/Title:

*If you are signing up to speak at already scheduled meetup, please provide the title of the meetup so that we can follow up with availability and update the appropriate agenda.*

## For Speakers

- [x] Complete [Speaker Questionnaire](https://goo.gl/forms/Om4MAebK7TagwT3L2) (First-time speakers)
- [x] Add Speaker Bio
- [x] Add shareable link to talk

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [x] Acquire a venue, if the talk is not part of an already scheduled event.
- [x] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [x] Draft of event started on Meetup.com
- [x] Confirm venue, sponsorship, and date.
- [x] Publish event to Meetup.com - Update event date above.
- [ ] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by marwan-at-work** [comment]
## Scheduling Details

Speaker(s): Marwan Sulaiman

Topic(s): Contributing To Athens

Event Date/Title:

https://www.meetup.com/golanguagenewyork/events/256371010/

## For Speakers

Bio: Marwan writes Go at The New York Times and is a contributor to the Athens project.

**Comment by Yigenana** [comment]
Speaker: Jonas
Topic: Women Who Go
Bio: Jonas is the organizer for Women Who Go NYC and a software engineer at Teachers Pay Teachers.
Slides: [Google Slides](https://docs.google.com/presentation/d/1d8S_nq-jElchPBtKgX1YHQZvvVYc3y1WumMLrtrlX2I/edit?usp=sharing)

**Comment by nywilken** [comment]
@marwan-at-work @Yigenana thank you for signing up to speak. I really appreciate it and look forward to see you tomorrow.

**Comment by t-0-m-1-3** [comment]
Scheduling Details
Speaker(s): Tom Goodheart

Topic(s): gx0re: a framework for analyzing malware

For Speakers
Bio: Tom is economically trained and security curious. He loves exposing people to go, git, and eating for free at meetups

Event date/title: next meetup
