### ISSUE TITLE
Lightning Talk for July 26 Summer Kickoff

### ISSUE THREAD

**Issue by crazcalm** [nycgolang/meetups#2]
## Scheduling Details

Speaker(s): Marcus Willock

Topic(s):
Title: How to modify Golang's default FileServer to hide dot files.
Summary: The talk will go over the process  which is
1. Finding the source code for Golang's FileServer
2. Figuring out where the needed changes should be applied.
3. Copying over all needed functions, methods and structs (A lot of them are non-exported) to a file you can use.
4. Make needed changes.
5. Check your work

This is based off of one of my recent projects (https://github.com/crazcalm/serve-it) 

Event Date/Title:
Event date - July 26th
Title - Go Language NYC Summer Kickoff 

*If you are signing up to speak at already scheduled meetup, please provide the title of the meetup so that we can follow up with availability and update the appropriate agenda.*

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [ ] Acquire a venue, if the talk is not part of an already scheduled event.
- [ ] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [ ] Draft of event started on Meetup.com
- [ ] Confirm venue, sponsorship, and date.
- [ ] Publish event to Meetup.com - Update event date above.
- [ ] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by nywilken** [comment]
@crazcalm thanks for signing up. Looking forward to hearing more about the work you did. I’m going to mark this issue as pending. Once added to the agenda I’ll mark as scheduled.

**Comment by crazcalm** [comment]
@nywilken Understood. Thanks!

**Comment by nywilken** [comment]
Agenda has been updated. Please let me know if you need to make any changes. I’ll confirm with you a couple of days before the event. Thanks again

**Comment by crazcalm** [comment]
Will do! Thanks! See you at the event!
