### ISSUE TITLE
Jan. 29: Reading and Writing Workshop

### ISSUE THREAD

**Issue by nywilken** [nycgolang/meetups#20]
## Scheduling Details

Speaker(s): Ayan George 

Topic(s):
Reading and Writing: A Tour of the io Package with Applications and Exercises

Event Date/Title: 1/20/2019 @ Google 

*If you are signing up to speak at already scheduled meetup, please provide the title of the meetup so that we can follow up with availability and update the appropriate agenda.*

## For Speakers

- [x] Complete [Speaker Questionnaire](https://goo.gl/forms/Om4MAebK7TagwT3L2) (First-time speakers)
- [x] Add Speaker Bio
- [ ] Add shareable link to talk

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [x] Acquire a venue, if the talk is not part of an already scheduled event.
- [x] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [x] Draft of event started on Meetup.com
- [x] Confirm venue, sponsorship, and date.
- [x] Publish event to Meetup.com - Update event date above.
- [x] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by ayang64** [comment]
i/o workshop slides, images, etc.

https://github.com/ayang64/ioworkshop

**Comment by nywilken** [comment]
Thanks man! I’ll link to it on our meetups repo as well. Good stuff. I’m
late on the posting but thanks for following up with the group. Safe
travels home. We will catch up soon.
--
Wilken Rivera <dev@wilkenrivera.com>



On Wed, Jan 30, 2019, at 2:19 PM, Ayan George wrote:
> i/o workshop slides, images, etc.


> https://github.com/ayang64/ioworkshop


> — You are receiving this because you were assigned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/golangnyc/meetups/issues/20#issuecomment-459073115

**Comment by mlitanin** [comment]
this is amazing, thank you!!
I had a question about slowwriter, accoridng to this function:

func (s slowWriter) Write(b []byte) (int, error) {
time.Sleep(s.delay * time.Duration(len(b)))
return s.w.Write(b)
}

it will sleep only once and then write it all.

but if we need to actually slow down writing - does it make sense to write
consequently X bytes based on given bps*8 in a loop until all bytes are
written?




--
*Max*
New York
+1 917-607-1136

maxim.puzin@gmail.com
*https://www.linkedin.com/in/litaninmaksym/
<https://www.linkedin.com/in/litaninmaksym/>*

**Comment by ayang64** [comment]
You make a good point.  I guess it depends on what you want to achieve.

If you want the r reader to have to deal with a trickle of bytes one at a
time, then what you propose makes sense.

If you're only interested in sending bytes - on average - at your specified
rate then maybe my way is okay.

About to take off... Will respond in detail once I get home.

**Comment by mlitanin** [comment]
i got your point,
thank you for the workshop, was really helpful to get into details of io
Reader/Writer interface implementation.

--
*Max*
New York
+1 917-607-1136

maxim.puzin@gmail.com
*https://www.linkedin.com/in/litaninmaksym/
<https://www.linkedin.com/in/litaninmaksym/>*
