### ISSUE TITLE
August 23 Go Meetup: Buffalo: Web Application Development is fun again in Go -- with easy testability!

### ISSUE THREAD

**Issue by robbyoconnor** [nycgolang/meetups#6]
## Scheduling Details

Speaker(s): **Robert O'Connor**

Topic(s): **Buffalo: Web Application Development is fun again in Go -- with easy testability!** 

Buffalo is a Go web application framework that inherits a lot of the things which makes Rails amazing -- it's a pleasure to work with too!

I will walk through how to set up a [Buffalo](http s://gobuffalo.io) application and show how easy it is to test your web application as you go. I will build a RESTful API in no time at all with full test coverage. 

Event Date/Title **:August 23: Go Meetup**

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [x] Acquire a venue, if the talk is not part of an already scheduled event.
- [x] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [x] Draft of event started on Meetup.com
- [x] Confirm venue, sponsorship, and date.
- [x] Publish event to Meetup.com - Update event date above.
- [x] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by nywilken** [comment]
@robbyoconnor thanks for signing up to talk. The topic sounds great and will be especially helpful to a number of new members I’ve spoken to recently. To better help get you situated for the upcoming event could you take a few minutes to complete the [speaker questionnaire](
https://goo.gl/forms/Om4MAebK7TagwT3L2)

**Comment by robbyoconnor** [comment]
@nywilken Done.

**Comment by robbyoconnor** [comment]
I'd be live-coding a bit -- so full-length would be nice.

**Comment by nywilken** [comment]
Great thanks. I’ll update this issue once I add your talk to the meetup event. Thanks again for signing up to speak.

**Comment by robbyoconnor** [comment]
Looking forward!

**Comment by nywilken** [comment]
Added to the event. I’m waiting for a description for the other talk before adding yours. Looking forward to the talk.

**Comment by robbyoconnor** [comment]
Is it possible to have two friends of mine come -- I know the meetup is
at capacity...
