### ISSUE TITLE
Go with C. Lightning Talk

### ISSUE THREAD

**Issue by moficodes** [nycgolang/meetups#8]
## Scheduling Details

Speaker(s): Mofizur Rahman

Topic(s): Go with C. Pros and Cons and general practices.

Event Date/Title: August 23: Go Meetup
*If you are signing up to speak at already scheduled meetup, please provide the title of the meetup so that we can follow up with availability and update the appropriate agenda.*

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [x] Acquire a venue, if the talk is not part of an already scheduled event.
- [x] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [x] Draft of event started on Meetup.com
- [x] Confirm venue, sponsorship, and date.
- [x] Publish event to Meetup.com - Update event date above.
- [x] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by nywilken** [comment]
@moficodes thanks for signing up for a lightning talk. I'm modified your title slightly and added a description based off our conversation. Let me know if you want me to adjust anything. 

```
"Go with C. The pros and cons of cgo."

A talk on the general practices of using Go with C, and lessons learned along the way.
```
