### ISSUE TITLE
Semantic Versioning In The Go Command

### ISSUE THREAD

**Issue by marwan-at-work** [nycgolang/meetups#9]
## Scheduling Details

Speaker(s):
Marwan Sulaiman
Topic(s):
Go Modules, Athens
Event Date/Title:
August 23

### First Steps
- [x] Self-assign the issue
- [x] Ping the person who opened the issue

### Pre-Scheduling Checklist
- [x] Add `pending` label to issue
- [x] Acquire a venue, if the talk is not part of an already scheduled event.
- [x] Acquire sponsorship for food and drinks

### Scheduling Checklist
- [x] Draft of event started on Meetup.com
- [x] Confirm venue, sponsorship, and date.
- [x] Publish event to Meetup.com - Update event date above.
- [x] Notify #nyc channel on Slack at https://invite.slack.golangbridge.org
- [x] Add `scheduled` label to issue

A couple weeks before the event
    Work with the venue host, and sponsor(s) to place order for food and drinks, if applicable

**Comment by nywilken** [comment]
Awesome! Scheduled and added to the event.
